#!/usr/bin/env python3
#
# generate_reference.py - Generate reference values for testing
#

import os
import sys
import numpy as np
from scipy import linalg, stats

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "..", "tests", "data")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def export_header(filename, **arrays):
    """Export arrays as C header file."""
    filepath = os.path.join(OUTPUT_DIR, filename)
    with open(filepath, "w") as f:
        f.write(f"/* Auto-generated by {os.path.basename(__file__)} */\n")
        f.write("#ifndef {}_H\n".format(filename.replace(".", "_").upper()))
        f.write("#define {}_H\n".format(filename.replace(".", "_").upper()))
        f.write("\n")
        for name, arr in arrays.items():
            if arr.ndim == 1:
                f.write(f"/* shape: ({arr.shape[0]},) */\n")
                f.write(f"static const double {name}[] = {{ ")
                f.write(", ".join(f"{v:.20e}" for v in arr))
                f.write(" };\n\n")
            elif arr.ndim == 2:
                f.write(f"/* shape: ({arr.shape[0]}, {arr.shape[1]}) */\n")
                f.write(f"static const double {name}[] = {{\n")
                for row in arr:
                    f.write("    " + ", ".join(f"{v:.20e}" for v in row) + ",\n")
                f.write("};\n\n")
        f.write("#endif /* {}_H */\n".format(filename.replace(".", "_").upper()))


def generate_gemm_reference():
    """GEMM reference data."""
    np.random.seed(42)
    A = np.random.randn(10, 8).astype(np.float64)
    B = np.random.randn(8, 6).astype(np.float64)
    C = A @ B
    export_header("ref_gemm.h", A=A, B=B, C=C)


def generate_stats_reference():
    """Statistics reference data."""
    np.random.seed(42)
    data = np.random.randn(100, 25).astype(np.float64)
    means = np.mean(data, axis=1)
    vars = np.var(data, axis=1, ddof=0)
    export_header("ref_stats.h", data=data, means=means, variances=vars)


def generate_linalg_reference():
    """Linear algebra reference data."""
    np.random.seed(42)
    A = np.random.randn(5, 5).astype(np.float64)
    A_psd = A @ A.T  # Positive semi-definite
    L = np.linalg.cholesky(A_psd)
    export_header("ref_linalg.h", A=A_psd, L=L)


def main():
    print("Generating reference values...")
    generate_gemm_reference()
    generate_stats_reference()
    generate_linalg_reference()
    print(f"Output: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
