// Package broker provides broker-specific order book management functionality.
package broker

// This file implements snapshot generation and distribution functionality.
// It provides snapshot builder and manages snapshot distribution to multiple subscribers.

import (
	"fmt"
	"time"

	"github.com/finosorg-labs/exchange"
)


// SnapshotBuilder builds order book snapshots from price level data.
// It encapsulates the snapshot generation logic and publisher coordination.
type SnapshotBuilder struct {
	publisher *SnapshotPublisher
}

// NewSnapshotBuilder creates a new snapshot builder.
func NewSnapshotBuilder() *SnapshotBuilder {
	return &SnapshotBuilder{
		publisher: NewSnapshotPublisher(),
	}
}

// Subscribe adds a snapshot subscriber.
// The subscriber will receive all future snapshots generated by BuildSnapshot.
func (sb *SnapshotBuilder) Subscribe(subscriber SnapshotSubscriber) error {
	return sb.publisher.Subscribe(subscriber)
}

// BuildSnapshot generates an order book snapshot from price level data.
// Parameters:
//   - symbolID: Symbol identifier
//   - bids: Top N bid price levels (descending order)
//   - asks: Top N ask price levels (ascending order)
//   - topN: Maximum number of price levels per side
//   - precision: Volume aggregation precision mode
//   - timestamp: Snapshot timestamp
//   - tickSize: Price unit for converting int64 prices to float64 (e.g., 0.001 means price 10250 = 10.25)
//
// Returns the generated snapshot or an error if generation fails.
func (sb *SnapshotBuilder) BuildSnapshot(
	symbolID uint32,
	bids []*PriceLevel,
	asks []*PriceLevel,
	topN int,
	precision exchange.OrderBookPrecisionMode,
	timestamp time.Time,
	tickSize float64,
) (*Snapshot, error) {
	if topN < 0 {
	return nil, fmt.Errorf("topN must be non-negative: %d", topN)
	}
	if tickSize <= 0 {
		return nil, fmt.Errorf("tickSize must be positive: %f", tickSize)
	}

	orders := make([]exchange.Order, 0, topN+topN)
	orders = appendLevels(orders, symbolID, bids, exchange.OrderBookSideBid, timestamp, tickSize)
	orders = appendLevels(orders, symbolID, asks, exchange.OrderBookSideAsk, timestamp, tickSize)

	snapshot, err := exchange.GenerateSnapshot(orders, uint32(topN), precision, timestamp)
	if err != nil {
		return nil, err
	}

	return snapshot, nil
}

// BuildAndPublish generates an order book snapshot and publishes it to all subscribers.
// This is a convenience method that combines BuildSnapshot and Publish.
//
// Returns the generated snapshot or an error if generation or publication fails.
func (sb *SnapshotBuilder) BuildAndPublish(
	symbolID uint32,
	bids []*PriceLevel,
	asks []*PriceLevel,
	topN int,
	precision exchange.OrderBookPrecisionMode,
	timestamp time.Time,
	tickSize float64,
) (*Snapshot, error) {
	snapshot, err := sb.BuildSnapshot(symbolID, bids, asks, topN, precision, timestamp, tickSize)
	if err != nil {
		return nil, err
	}

	if err := sb.publisher.Publish(snapshot); err != nil {
		return nil, err
	}

	return snapshot, nil
}

// appendLevels converts price levels to exchange orders for snapshot generation.
// Helper function used by BuildSnapshot.
//
// Parameters:
//   - tickSize: Price unit for converting int64 to float64 (e.g., 0.001 for stocks)
//        Example: if level.Price = 10250 and tickSize = 0.001, then float price = 10.25
func appendLevels(
	orders []exchange.Order,
	symbolID uint32,
	levels []*PriceLevel,
	side exchange.OrderBookSide,
	timestamp time.Time,
	tickSize float64,
) []exchange.Order {
	for _, level := range levels {
		if level == nil {
			continue
		}
		orders = append(orders, exchange.Order{
			SymbolID:  symbolID,
			Price:     float64(level.Price) * tickSize, // Convert int64 price to float64
		Volume:    float64(level.TotalQty),          // Volume can be directly converted
			Side:      side,
			Timestamp: timestamp,
		})
	}
	return orders
}

