# =============================================================================
# InstallConfig.cmake - Installation configuration
# =============================================================================

# Install CMake config files
install(
    FILES
        "${CMAKE_CURRENT_SOURCE_DIR}/cmake/DetectSIMD.cmake"
        "${CMAKE_CURRENT_SOURCE_DIR}/cmake/CompilerFlags.cmake"
    DESTINATION share/fin-kit/cmake
)

# Install version header (generated by top-level configure_file)
# Binary dir is injected via @ONLY substitution, no CMake variable needed here
install(
    FILES "${CMAKE_BINARY_DIR}/include/fin-kit/version.h"
    DESTINATION include/fin-kit
)
